config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    # registrations: 'users/registrations' # rails g devise:controllers users
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :publications do
    member do
      post "contact_email"
    end
  end

  # Routes

  #get 'pages/account'
  #get 'pages/index'

  resources :pages, only: [:index] do
    collection do
      get 'account'
    end
  end

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  #mount_uploader :photo, PhotoUploader

  belongs_to :user
  belongs_to :commune, optional: true
  belongs_to :region, optional: true
  belongs_to :category, optional: true
  belongs_to :type, optional: true

  has_many :shipping_equipments, dependent: :destroy
  has_many :equipments, through: :shipping_equipments

  has_many :publication_attachments, dependent: :destroy
  accepts_nested_attributes_for :publication_attachments

  attr_accessor :equipments_ids

  geocoded_by :address
  after_validation :geocode

  # Validations
  validates :title, length: { maximum: 50 }
  validates :title, presence: {message_: "Título es requerido" }
  validates :description, presence: {message: "Descripción es requerida"}
  validates :address, presence: {message: "Dirección es requerida"}

  # Scopes
  scope :by_title, -> (search) { where("title ilike ? OR description ilike ?", "%#{search}%", "%#{search}%") }
  scope :by_type, -> (search) { where(type_id: search) }
  scope :by_region, -> (search) { where(region_id: search) }
  scope :by_commune, -> (search) { where(commune_id: search) }
  scope :by_region2, -> (search) { where(region2_id: search) }
  scope :by_commune2, -> (search) { where(commune2_id: search) }
  scope :by_width_min, -> (value_min) { where("width >= ?", value_min) }
  scope :by_width_max, -> (value_max) { where("width <= ?", value_max) }
  scope :by_length_min, -> (value_min) { where("length >= ?", value_min) }
  scope :by_length_max, -> (value_max) { where("length <= ?", value_max) }
  scope :by_height_min, -> (value_min) { where("height >= ?", value_min) }
  scope :by_height_max, -> (value_max) { where("height <= ?", value_max) }

  def next
    Publication.where(["id > ?", id]).first
  end

  def prev
    Publication.where(["id < ?", id]).last
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :set_all, only: [:index, :show, :new, :edit, :create]
  before_action :access_user, only: [:edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index

    @publications = Publication.all.includes(:region, :commune, :publication_attachments) #Bulllet
    @publications = @publications.by_title(params[:search_title]) if params[:search_title].present?
    @publications = @publications.by_type(params[:search_type]) if params[:search_type].present?
    @publications = @publications.by_address(params[:search_address]) if params[:search_address].present?
    @publications = @publications.by_region(params[:search_region]) if params[:search_region].present?
    @publications = @publications.by_commune(params[:search_commune]) if params[:search_commune].present?
    @publications = @publications.by_address2(params[:search_address2]) if params[:search_address2].present?
    @publications = @publications.by_region2(params[:search_region2]) if params[:search_region2].present?
    @publications = @publications.by_commune2(params[:search_commune2]) if params[:search_commune2].present?
    @publications = @publications.by_width_min(params[:width_min]) if params[:width_min].present?
    @publications = @publications.by_width_max(params[:width_max]) if params[:width_max].present?
    @publications = @publications.by_length_min(params[:length_min]) if params[:length_min].present?
    @publications = @publications.by_length_max(params[:length_max]) if params[:length_max].present?
    @publications = @publications.by_height_min(params[:height_min]) if params[:height_min].present?
    @publications = @publications.by_height_max(params[:height_max]) if params[:height_max].present?
    @publications = @publications.by_latitude_min(params[:latitude_min]) if params[:latitude_min].present?
    @publications = @publications.by_latitude_max(params[:latitude_max]) if params[:latitude_max].present?
    @publications = @publications.by_longitude_min(params[:longitude_min]) if params[:longitude_min].present?
    @publications = @publications.by_longitude_max(params[:longitude_max]) if params[:longitude_max].present?
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication.page_views += 1
    @publication.save
    @publication_attachments = @publication.publication_attachments.all

    @publications = Publication.all
  end

  def contact_email
    @publication = Publication.find(params[:id])
    UserMailer.contact_send(current_user, @publication, params[:name_sent], params[:phone_sent], params[:email_sent], params[:message_sent]).deliver_now()
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    @publication_attachment = @publication.publication_attachments.build
    @categories = Category.all
    @regions = Region.all.includes(:communes)
  end

  # GET /publications/1/edit
  def edit
  end

  def access_user
    unless @publication.user == current_user
      flash[:alert] = 'Access denied'
      redirect_to pages_path
    end
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = current_user.publications.new(publication_params)

    respond_to do |format|
      if @publication.save
        unless params[:publication_attachments].nil?
          params[:publication_attachments]['photo'].each do |a|
             @publication_attachment = @publication.publication_attachments.create!(:photo => a)
          end
        end
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

     def set_all
      @categories = Category.all
      @types = Type.all
      @regions = Region.all
      @communes = Commune.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:user_id, :title, :width, :length, :height, :description, :address, :address2, :price, :category_id, :type_id, :region_id, :commune_id, :region2_id, :commune2_id, equipments_ids: [], publication_attachments_attributes: [:id, :publication_id, :photo, :photo_cache])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/contact_email.js.erb
$("#name_sent").val("");
$("#phone_sent").val("");
$("#email_sent").val("");
$("#message_sent").val("");
$('.alert').show();

app/views/publications/edit.html.erb
  <div class="container">
    <section class="new-shipping">
      <div class="row">
        <div class="col-md-12 text-center">
          <h2>Editar Aviso</h2>
          <br>
        </div>
      </div>
      <!-- Formulario de New Shipping -->
      <%= render 'form', publication: @publication %>

      <!-- Datos de Contacto -->
      <%# render 'form', publication: @publication %>
    </section>
  </div>

app/views/publications/index.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center title-up">
        <% if user_signed_in? %>
          <%= link_to "Publica Ahora!", new_publication_path, class: 'btn btn-primary btn-xl btn-new bold' %>
        <% end %>
        <h2>Avisos de Envios</h2>
      </div>
    </div>
      <div class="row">
        <div class="col-md-3">
         <div class="form-index">
           <%= form_tag(publications_path, method: :get, class:"form") do %>
           <div class="well">
             <h3 class="text-center title-up">Buscador</h3>
             <div class="form-group">
               <%= label :type, "Tipo de Envio" %>
               <%= select_tag :search_type, options_from_collection_for_select(@types, :id, :name), prompt: "Escoge un tipo de envio", class: 'form-control form-control-input' %>
             </div>

             <div class="form-group">
               <%= label :region, "Región Origen" %>
               <%= select_tag :search_region, options_from_collection_for_select(@regions, :id, :name), prompt: "Selecciona una Región Origen", class: 'form-control' %>
             </div>
             <div class="form-group">
               <%= label :commune, "Comuna Origen" %>
               <%= select_tag :search_commune, options_from_collection_for_select(@communes, :id, :name), prompt: "Selecciona la Comuna Origen", class: 'form-control' %>
             </div>

             <div class="form-group">
               <%= label :width, "Ancho" %>
               <div class="row">
                 <div class="col-md-12">
                   <div class="input-group">
                     <div class="input-group-addon">
                       <i class="fa fa-minus-circle" aria-hidden="true"></i>
                     </div>
                     <%= select_tag :width_min, options_for_select([['30 cms', '1'],['50 cms', '2'],['80 cms', '3'],['90 cms', '4'],['otro', '5']]),class: 'form-control', include_blank: true %>
                   </div>
                 </div>
               </div>
             </div>
             <div class="form-group">
               <%= label :length, "Largo" %>
               <div class="row">
                 <div class="col-md-12">
                   <div class="input-group">
                     <div class="input-group-addon">
                       <i class="fa fa-minus-circle" aria-hidden="true"></i>
                     </div>
                     <%= select_tag :length_min, options_for_select([['30 cms', '1'],['50 cms', '2'],['80 cms', '3'],['90 cms', '4'],['otro', '5']]),class: 'form-control', include_blank: true %>
                   </div>
                 </div>
               </div>
             </div>
             <div class="form-group">
               <%= label :height, "Alto" %>
               <div class="row">
                 <div class="col-md-12">
                   <div class="input-group">
                     <div class="input-group-addon">
                       <i class="fa fa-minus-circle" aria-hidden="true"></i>
                     </div>
                     <%= select_tag :height_min, options_for_select([['30 cms', '1'],['50 cms', '2'],['80 cms', '3'],['90 cms', '4'],['otro', '5']]),class: 'form-control', include_blank: true %>
                   </div>
                 </div>
               </div>
             </div>
             <br>
             <div class="form-group">
               <div class="row">
                 <div class="col-md-6">
                   <span class="input-group-btn">
                     <%= link_to publications_path, class: "btn btn-warning btn-sm btn-block" do %>
                      Limpiar
                     <% end %>
                   </span>
                 </div>
                 <div class="col-md-6">
                   <span class="input-group-btn">
                     <%= button_tag(type: "submit", class: "btn btn-primary btn-sm btn-block") do %>
                      Buscar
                     <% end %>
                   </span>
                 </div>
               </div>
               <br>
            </div>
          </div>
          <% end %>
        </div>
        </div>

        <div class="col-md-9">
          <div class="row">
           <% @publications.each do |publication| %>
           <div class="col-md-4">
            <div class="thumbnail display-index">
              <%= link_to (image_tag(publication.publication_attachments.first.photo.thumb, class: 'img-responsive')), publication unless publication.publication_attachments.empty? %>
              <div class="caption text-center">
                <h4><%= publication.title %></h4>
                <hr class= "separator">
                <div class="show-index-publications">
                  <%= image_tag 'ubication.png', class: 'img-ico-index' %>
                  <%= publication.region.name if publication.region_id %>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="show-index-publications">
                      <%= image_tag 'location.png', class: 'img-ico-index' %>
                      <%= publication.commune.name %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="show-index-publications">
                      <%= image_tag 'dollar.png', class: 'img-ico-index-dollar' %>
                      <strong><%= publication.price unless publication.price.nil? %></strong>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/publications/new.html.erb
  <div class="container">
    <section class="new-shipping">
        <div class="row">
          <div class="col-md-12 text-center">
            <h2>Nuevo Aviso</h2>
            <br>
          </div>
        </div>
        <!-- Formulario de New Shipping -->
        <%= render 'form', publication: @publication %>
    </section>
  </div>

app/views/publications/show.html.erb
  <div class="container">
    <section class="show-shipping">
      <%# if can? :manage, Publication %>
        <%#= link_to 'Edit', edit_publication_path(@publication) %>
        <%#= link_to 'Back', publications_path %>
      <%# end %>
      <div class="row">
        <div class="col-md-12 text-center">
          <h2><%= @publication.title %></h2>
          <hr class="separator">
        </div>
        <% if @publication.user == current_user %>
          <div class="row">
            <div class="col-md-3 show-information">
              <%= link_to edit_publication_path(@publication), class: 'btn btn-primary ink-left' do %>
                Editar
              <% end %>
              <%= link_to @publication, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger link-left' do %>
                Eliminar
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="row">
            <div class="col-md-4 show-information">
              <%= image_tag 'ubication.png', class: 'img-ico-show' %>
              <%= @publication.region.name unless @publication.region_id.nil? %>
            </div>
            <div class="col-md-4 show-information">
              <i class="fa fa-eye text-primary" aria-hidden="true"></i>
              <span><%= @publication.page_views %></span>
            </div>

            <div class="col-md-4 show-information">
              <i class="fa fa-usd text-success" aria-hidden="true"></i>
              <strong><%= @publication.price unless @publication.price.nil? %></strong>
            </div>
          </div>
        <% end %>
      </div>
      <br><br>
      <div class="row">
        <div class="col-md-6">
          <div class="thumbnail">
            <div class="carousel-show">
              <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner image-publication" role="listbox">
                  <% @publication_attachments.each_with_index do |element, index| %>
                    <% if index == 0 %>
                      <div class="item active">
                        <%= image_tag element.photo %>
                      </div>
                    <% else %>
                      <div class="item">
                        <%= image_tag element.photo %>
                      </div>
                    <% end %>
                  <% end %>
                  <% if @publication.category.name == "Subasta" %>
                    <%= image_tag 'Subasta-img.png', class: 'img-notice' %>
                  <% else %>
                    <%= image_tag 'Envio-img.jpg', class: 'img-notice-sale' %>
                  <% end %>
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">

                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <hr class="separator-show">
              <div class="row">
                <div class="caption">
                  <div class="col-md-5">
                    <p class="text-show-photo"><%= image_tag 'ubication.png', class: 'img-ico-show-photo' %>
                    <%= @publication.region.name unless @publication.region_id.nil? %></p>
                    <p class="text-show-photo"><%= image_tag 'location.png', class: 'img-ico-show-photo' %>
                    <%= @publication.commune.name unless @publication.region_id.nil? %></p>
                    <p class="text-show-photo"><%= image_tag 'Calendar-ico.png', class: 'img-ico-show-photo' %>
                    <span><%= @publication.created_at.strftime("%d de %B") %></span>
                  </div>
                  <div class="col-md-6">
                    <p class="text-show-photo"><%= image_tag 'user.png', class: 'img-ico-show-dollar-photo' %>
                      <%= @publication.user.name %></p>
                    <p class="text-show-photo-email"><%= image_tag 'email.png', class: 'img-ico-show-dollar-photo' %>
                      <%= @publication.user.email %></p>
                    <p class="text-show-photo"><%= image_tag 'cell.png', class: 'img-ico-show-dollar-photo' %>
                      <%= @publication.user.phone %></p>
                  </div>
                  <div class="col-md-1">
                    <%= image_tag(@publication.user.avatar, class: 'img-profile-show-photo img-circle') %>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <div class="col-md-6">
          <div class="show-description">
            <p class="text-show-shipping">
              <strong>Descripción:</strong></p>
            <p class="text-show-shipping">
              <%= @publication.description %></p>
          </div>
          <div class="show-information">
            <i class="fa fa-usd text-success" aria-hidden="true"></i>
            <strong><%= @publication.price unless @publication.price.nil? %> pesos</strong>
          </div>
          <div class="show-group">
            <p class="text-show-shipping">
              <%= image_tag 'address-ico.png', class: 'img-ico' %>
              <strong>Dirección Origen:</strong>
              <%= @publication.address %>
            </p>
          </div>
          <div class="show-group">
            <p class="text-show-shipping">
              <%= image_tag 'address-ico.png', class: 'img-ico' %>
              <strong>Dirección Destino:</strong>
              <%= @publication.address2 %>

            </p>
          </div>
          <div class="show-group">
            <p class="text-show-shipping">
              <%= image_tag 'camion-de-reparto-ico.png', class: 'img-ico' %>
              <strong>Tipo de Envio:</strong>
              <%= @publication.type.name unless @publication.type_id.nil? %>
            </p>
          </div>
          <div class="show-group">
            <p class="text-show-shipping">
              <%= image_tag 'measure-tape-ico.png', class: 'img-ico' %>
              <strong>Ancho:</strong>
              <%= @publication.width %>
              <strong>Largo:</strong>
              <%= @publication.length %>
              <strong>Alto:</strong>
              <%= @publication.height %>
            </p>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-6">

          <div class="show-group">
            <p class="text-show-shipping">
              <strong>Ubicación:</strong></p>
            <div id="map" class="map-google"></div>

            <!-- Script Geolocalizacón -->

            <script src="https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

            <script>
              function initMap(){
                handler = Gmaps.build('Google');
                handler.buildMap({
                  provider: {
                    zoom: 16,
                    center: {
                      lat: <%= @publication.latitude %>,
                      lng: <%= @publication.longitude %>
                    }
                  },
                  internal: {id: 'map'}
                },
                function(){
                  markers = handler.addMarkers([{
                    lat: <%= @publication.latitude %>,
                    lng: <%= @publication.longitude %>,

                  }]);
                });
              };
            </script>

            <script src="https://maps.google.com/maps/api/js?key=AIzaSyChBYkswOMFSQyG39OjwXPvC8EKePxKoVc&callback=initMap" async defer></script>

            <!-- end -->

          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <div class="col-md-offset-2 col-md-8">
              <div class="panel panel-default">
                <div class="panel-heading text-center">
                  <h4><strong>Contacta al Vendedor</strong></h4>
                </div>
                <div class="panel-body">
                  <%= form_tag(contact_email_publication_path(@publication), {class:'form-horizontal', id:'form-email', method: :post, remote: true}) do %>
                    <div class="col-md-12">
                      <div class="form-group">
                        <%= label_tag :name_sent, "Nombre:" %>
                        <%= text_field_tag :name_sent, nil, class: 'form-control', required: true %>
                      </div>
                      <div class="form-group">
                        <%= label_tag :phone_sent, "Celular:" %>
                        <%= phone_field_tag :phone_sent, nil, class: 'form-control', required: true %>
                      </div>
                      <div class="form-group">
                        <%= label_tag :email_sent, "E-mail:" %>
                        <%= email_field_tag :email_sent, nil, class: 'form-control', required: true %>
                      </div>
                      <div class="form-group">
                        <%= label_tag :message_sent, "Mensaje:" %>
                        <%= text_area_tag :message_sent, nil, class: 'form-control', required: true %>
                      </div>
                      <div class="form-group">
                        <%= submit_tag "Enviar", class: 'btn btn-success btn-sm', id:'new-email' %>
                        <div class="alert alert-success alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                          Listo! Mensaje enviado correctamente.
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>

            <script>
              function validateForm(){
                $("#form-email").validate({
                  debug: true,
                  rules: {
                    name_sent: {required: true},
                    phone_sent: {required: true, minlength: 8, maxlength: 9},
                    email_sent: {required: true, email: true},
                    message_sent: {required: true}
                  },
                  messages: {
                    name_sent: "Ingresa tu nombre",
                    phone_sent: "Ingresa tu celular",
                    email_sent: "Debes ingresar un e-mail valido",
                    message_sent: "Debes ingresar tu mensaje"
                  }
                });
                $("#new-email").click(function(event) {
                  event.stopPropagation();
                });
              }
              $(document).on('turbolinks:load', function(){
                validateForm();

              });

            </script>
          </div>
        </div>
      </div>
      <br>
      <hr class="separator">
      <div class="row">
        <div class="col-md-4 text-center">
          <%= link_to "Aviso Anterior", @publication.prev %>
        </div>
        <div class="col-md-4 text-center">
          <%= link_to 'Volver a Avisos', publications_path %>
        </div>
        <div class="col-md-4 text-center">
          <%= link_to "Próximo Aviso", @publication.next %>
        </div>
      </div>
    </div>
  </section>
</div>