config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    # registrations: 'users/registrations' # rails g devise:controllers users
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :publications do
    member do
      post "contact_email"
    end
  end

  # Routes

  #get 'pages/account'
  #get 'pages/index'

  resources :pages, only: [:index] do
    collection do
      get 'account'
    end
  end

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

<section id="contact">
  <footer class="footer-distributed">

    <div class="footer-left">
      <%= link_to (image_tag('go.png', class: 'img-logo img-responsive')), pages_path %>
      <p class="footer-links">
        <%= link_to "Inicio", pages_path, class: 'page-scroll' %>
        ·
        <a class="page-scroll" href="#about">Últimos Avisos</a>
        ·
        <a class="page-scroll" href="#services">Beneficios</a>
        ·
        <a class="page-scroll" href="#contact">Contacto</a>
      </p>

      <hr class="separator">
      <p class="footer-company-name">Denisse Velásquez Salazar &copy; 2018</p>

    </div>


    <div class="footer-center">
      <div>
        <i class="fa fa-map-marker"></i>
        <p>Santiago, Chile</p>
      </div>
      <div>
        <i class="fa fa-phone"></i>
        <p>+56 9 7768 1699</p>
      </div>
      <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:contacto@goshipping.com">contacto@goshipping.com</a></p>
      </div>
    </div>

    <div class="footer-right">
      <p class="footer-company-about">
        <span>Go Shipping</span>
        Contáctate con nosotros!
      </p>

      <div class="footer-icons">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
      </div>
    </div>
  </footer>
</section>

app/views/shared/_home.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <div class="row">
                <div class="col-md-12">
                    <h2 id="homeHeading" class="home-title">¿Necesitas realizar un envío? <span class="bold">Encuentra tu transportista</span></h2>
                    <br>
                </div>
                <div class="col-md-12">
                    <h2 id="homeHeading" class="home-title">¿Tienes espacio en tu vehículo? <span class="bold">Encuentra un envío al lugar que viajas</span></h2>
                    <br>
                </div>
               <hr>
           </div>
           <br><br><br><br><br><br>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Avisos Recientes</a>
            <%= link_to "Publicar", new_publication_path, class: 'btn btn-primary btn-xl' %>
            <%= link_to "Ver Avisos", publications_path, class: 'btn btn-primary btn-xl' %>
        </div>
    </div>
</header>

app/views/shared/_latest_publications.html.erb
<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="section-heading">Últimos Avisos</h2>
        <hr class="light">
      </div>
      <div class="row">
        <% @publications.each do |publication| %>
         <div class="col-md-3">
          <div class="thumbnail display-index-latest">
            <%= link_to (image_tag(publication.publication_attachments.first.photo.thumb, class: 'img-responsive')), publication unless publication.publication_attachments.empty? %>
            <div class="caption text-center">
              <h4><%= publication.title %></h4>
            </div>      
          </div>
          <br>
        </div>
        <% end %>
      </div>
      <div class="col-md-12 text-center">
       <%= link_to "Ver Todo", publications_path, class: 'btn btn-warning btn-xl' %>
      </div>
      <!--
      <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started!</a>
    -->
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to (image_tag('go1.png', class: 'img-logo img-responsive')), pages_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Inicio", pages_path, class: 'page-scroll' %>
        </li>
        <li>
          <a class="page-scroll" href="/pages/#about">Últimos Avisos</a>
        </li>
        <li>
          <a class="page-scroll" href="/pages/#services">Beneficios</a>
        </li>
        <li>
          <a class="page-scroll" href="/pages/#contact">Contacto</a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? %>
              <%= image_tag(current_user.avatar, class: 'img-profile img-circle') %>
              <%= current_user.name %>
            <% else %>
              <strong>Entrar</strong>
            <% end %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <li><a href="<%= account_pages_path %>">Mi Cuenta <i class="fa fa-user" aria-hidden="true"></i></a></li>
                <li><a href="<%= edit_user_registration_path %>">Editar <i class="fa fa-wrench" aria-hidden="true"></i></a></li>
                <li class="divider"></li>
                <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Cerrar Sesión <i class="fa fa-power-off" aria-hidden="true"></i></a></li>
              <% else %>
                <li><a href="<%= new_user_session_path %>">Ingresar</a></li>
                <li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
                <li class="divider"></li>
                <li><a href="<%= new_admin_user_session_path %>">Administrador</a></li>
              <% end %>
            </ul>
          </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

app/views/shared/_notices.html.erb
    <h4>Actualmente tienes: <span class="badge"><%= @publications.count %></span> avisos</h4>
    <br>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover table-borderedt tabla">
          <thead>
            <th class="text-center">Estado</th>
            <th class="text-center">Aviso</th>
            <th class="text-center">Descripción</th>
            <th class="text-center">Precio</th>
            <th class="text-center">Administrar</th>
          </thead>
          <% @publications.each do |publication| %>
          <tbody class="text-center">
           <tr>
            <td class="col-md-1">
              <i class="fa fa-check check-icon" aria-hidden="true"></i>
            </td>
            <td class="col-md-2"><%= link_to (image_tag(publication.publication_attachments.first.photo.thumb, class: 'img-shipping-account img-thumbnail')), publication unless publication.publication_attachments.empty? %>
            </td>
            <td class="col-md-3 text-justify">
             <span><%= publication.created_at.strftime("%d de %B") %></span>
             <h4><b><%= publication.title %></b></h4>
             <p><%= publication.commune.name %></p>
             <i class="fa fa-eye" aria-hidden="true"></i>
             <span><%= publication.page_views %></span>
           </td>
           <td class="col-md-1">
             <p><b><%= publication.price %></b></p>
           </td>
           <td class="col-md-3">
             <%= link_to publication, class: 'btn btn-info btn-sm' do %>
             <span class="fa fa-eye"></span>
             <% end %>
             <%= link_to edit_publication_path(publication), class: 'btn btn-primary btn-sm' do %>
             <span class="fa fa-pencil"></span>
             <% end %>
             <%= link_to publication, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
             <span class="glyphicon glyphicon-trash"></span>
             <% end %>
           </td>
          </tr>
        </tbody>
        <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shared/_services.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Beneficios de Publicar</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-truck text-primary" aria-hidden="true"></i>
          <h3>Ingresa tus pedidos en forma rápida</h3>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-users text-primary" aria-hidden="true"></i>
          <h3>Elige que tipo de carga deseas transportar</h3>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa fa-star-half-o text-primary sr-icons" aria-hidden="true"></i>
          <h3>Califica tu transporte</h3>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-road text-primary sr-icons" aria-hidden="true"></i>
          <h3>Transporta al mejor precio</h3>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
        </div>
      </div>
    </div>
  </div>
</section>